org: saichand
app: aws-node-practise
service: aws-node-practise

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello-short:
    handler: handler.hello
    timeout: 3
    memorySize: 128
    description: short function
  hello-long:
    handler: handler.hello
    timeout: 6
    memorySize: 256
    description: long function
